In [1]:
import pandas as pd   #importing pandas because it help for various operation in tabular form , also helps to see the meaningful insights in the table - i created the alias name for pandas as =>pd for ease to use multiple time 
data=pd.read_csv("Salary_Data.csv")       #here the dataset has been readed with the help of pandas library and stored it in the 'data' variable and also modification in this dataset does not affect the original dataaset

In [2]:
data #here the data variable is printed for checking whether out imported dataset is correct or not

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [3]:
# Input and Output split :
feature = data[["YearsExperience"]]      # here the feature or input column is taken from the dataset-'data' and stored it in 'feature' variable
target = data[["Salary"]]     # here the output or target column is taken from the dataset-'data' and stored it in 'target' variable

# the input and output data has been splitted successfully

In [4]:
feature  # here just checking the input is correctly assigned in a 'feature'variable to reduce further errors 

YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [5]:
target       # here just checking the output is correctly assigned in a 'target'variable to reduce further errors 

Salary
0    39343
1    46205
2    37731
3    43525
4    39891
5    56642
6    60150
7    54445
8    64445
9    57189
10   63218
11   55794
12   56957
13   57081
14   61111
15   67938
16   66029
17   83088
18   81363
19   93940
20   91738
21   98273
22  101302
23  113812
24  109431
25  105582
26  116969
27  112635
28  122391
29  121872

In [6]:
# spliting of training and testing dataset 

from sklearn.model_selection import train_test_split       # from scikit learn library - inside model_selection class, we have imported the 'train_test_split' for seperating or spitting the training and testing dataset
x_train,x_test,y_train,y_test=train_test_split(feature,target,test_size=.20,random_state=0)      #here the 'train_test_split'-method occupies four parameters , 1.input , 2.output , 3.size of the test dataset to be split(test_size) , 4.random_state

#It returns the four different datasets , so we have created four different variables to store those datasets 

#the splitting of training and testing dataset has been successfully executed and splitted ....

In [7]:
x_train.count()  # just printing how many rows the 'x_train' variable consist of and what is the datatype present inside it 

YearsExperience    24
dtype: int64

In [8]:
x_test.count()       # just printing how many rows the 'x_test' variable consist of and what is the datatype present inside it 

YearsExperience    6
dtype: int64

In [9]:
y_train.count()          # just printing how many rows the 'y_train' variable consist of and what is the datatype present inside it 

Salary    24
dtype: int64

In [10]:
y_test.count()          # just printing how many rows the 'y_test' variable consist of and what is the datatype present inside it 

Salary    6
dtype: int64

In [11]:
#                                "  _______MODEL CREATION PHASE ________  "

# after splitting training and testing datasets , we need to create a model with the help of trainning dataset ...
# here we are going to create a model with training dataset


from sklearn.linear_model import LinearRegression   # from 'scikitlearn'-library , inside linear_model class , we imported 'LinearRegression'- it is an algorithm used to predict the variables given by end users using training dataset 
regressor=LinearRegression()    # just storing the 'LinearRegression'-(algorithm or class) in the variable called 'regressor'
regressor   #just printing the variable to see weather the method is stored in a assigned variable or not

LinearRegression()

In [12]:
# creation of model using training dataset => also called as training of the model

model_crt=regressor.fit(x_train,y_train)     #inside 'linearregression'- algorithm, there is a (method or function) called 'fit' which helps to train our model using training dataset ==>> we have already assigned the 'LinearRegression' in a variable so , using such variable with dot operator(.) to call the function  and store the trained model in another variable
model_crt     # just checking weather the trained model is stored in same variable or not  


# Model has been created successfully inside the variable called 'model_crt'....

LinearRegression()

In [13]:
# SLR (simple linear regression) formula :" y = w x + b "
# after creating the model => that is , filling out all the variables except input data on above formula , just checking weather the weight'w' and bias'b' is calculated or not 
weight = model_crt.coef_       #using coef_ method to see the variable of weight'w'
bias = model_crt.intercept_    #using intercept_ method to see the variable of weight'w'

In [14]:
weight    #just printing what is present inside the weight'w' variable

array([[9312.57512673]])

In [15]:
bias     #just printing what is present inside the bias'b' variable

array([26780.09915063])

In [16]:
#               """"   ___________DEPLOYMENT PHASE__________ """"

# testing stage : 
#after creating the model using training dataset , we have to test the model using the testing inputs => here 'x_test'

y_pred=model_crt.predict(x_test)    # inside 'linearregression' class , there is a method called 'predict' - with the help of predict method , your model will get tested with 'x_test'-input for any kind of prediction and stored it in another variable

# our AI model gets generated .....

In [17]:
y_pred        # just printing the output of the predicted model using 'x_test'-input

array([[ 40748.96184072],
       [122699.62295594],
       [ 64961.65717022],
       [ 63099.14214487],
       [115249.56285456],
       [107799.50275317]])

In [18]:
# after testing the model ,we have to know the value of predicted output  is correct or not , so we use r2_score to calculate the accuracy of our tested model- 'predicted output'

from sklearn.metrics import r2_score   # using scikit learn - metrics class => importing r2_score  ->  the r2_score will ranges from 0 to 1 : if the accuracy or result is near to 0 implies our model is not learned well , if its near to 1 then good model -> proceed to end users 
r_score = r2_score(y_test,y_pred)      # the r2_score method consist of two parameters to calculate the accuracy of predicted output from actual output (i.e)=>(actual_output-(y_test) and predicted_output-(variable of the predicted output - here(y_pred)))


In [19]:
r_score   # just seeing how accuracy is our model is ... It ranges from 0 to 1 : if the accuracy or result is near to 0 implies our model is not learned well , if its near to 1 then good model -> proceed to endusers

0.988169515729126

In [20]:
# SAVE THE BEST MODEL 
# the accuracy of our model is near to 1 , so we have to save this model and give to front end developer and made usable for end user

import pickle as pk    # pickle library is used for saving the model'created' inside python ide
store=pk.dump(model_crt,open("finalyzed_model.sav","wb"))     #we have to save out created model for further use -> dump method in pickle library is used for dumping-up or inserting  the model created in python 
# we have successfully saved the model in the name of : "finalyzed_model.sav"  , and "wb"-writebinary is nothing but creation of model used wb to write inside it 

In [21]:
load=pk.load(open("finalyzed_model.sav","rb"))  # just loaded the saved model for just checking up => deployment checkup 

In [22]:
load     # this output indicated out model has been successfully loaded on 'load' variable

LinearRegression()

In [23]:
# just checking our model with user inputs 

inp=float(input("Enter the years of Experience : "))    
result = load.predict([[inp]])  
result    # this result shows the final prediction of the model to the end user 


c:\Python\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[213031.60168521]])